spring:
  application:
    name: TrackingBot
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60s

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    webhook-secret: ${TELEGRAM_WEBHOOK_SECRET:}
